### ISSUE TITLE
Shows as 1D barcode on WatchOS 11 and AW Ultra

### ISSUE THREAD

**Issue by jhulance** [sargant/dfyb.run#63]
Hi! I guess this is because of the recent WatchOS update, but the pass was absent from my watch at this morning's parkrun. I went to reinstate it via your web site and that worked, but on my Apple Watch it now shows the barcode, not the nice, big QR code that it used to.

**Comment by Alsoff** [comment]
I came here to say something similar. This morning I still had my Parkrun pass in Apple Wallet but on my watch it had changed from being a QR code to a barcode. Only thing that has changed is the upgrade to WatchOS 11.

**Comment by Kikabyte** [comment]
Barcode has indeed altered to a standard barcode. It does still scan ok, just a bit slower.

**Comment by sargant** [comment]
The generated passes contain both Code 128 (1D) and QR (2D) barcodes - this is due to previous feedback where people were expecting to see a standard parkrun-style barcode.

To display the Code 128 barcode requires a sufficiently large, hi-res screen - and it falls back to the QR code for smaller, lower-res screens. Until recently, this meant phones showed traditional barcodes and watches showed the QR code. 

Presumably something changed in WatchOS 11 that means sufficiently small barcodes can now be displayed on the larger watches (the Ultra specifically).

I’ve been using it like this for a while - yes it’s a little slower, but I’m reticent to change it, as it would get rid of the standard barcode for people using it on their phone.

**Comment by Kikabyte** [comment]
Thanks for the info.
